spring.application.name=gambling-site-backend
server.port=8080
spring.data.mongodb.uri=mongodb+srv://gargkush2003:Kush1234@trainingdatabase.6b9udqa.mongodb.net/Betrix
jwt.secret=yourSecureSecret56576576876534655264
jwt.token-validity=36000000
security.config.permitted-endpoints=/api/users/**,/api/public/**,/api/wallet/**,/api/games/**,/api/transactions/**, /api/auth/**